### ISSUE TITLE
What does this library do?

### ISSUE THREAD

**Issue by stevenvachon** [gucong3000/postcss-html#1]
I'm confused by the readme. Why would we want to parse HTML/etc for PostCSS?

**Comment by gucong3000** [comment]
My original goal was to check the style of the code in the Vue component. just like `eslint-plugin-html`.

**Comment by stevenvachon** [comment]
I know what a Vue component is, but I don't understand the "check the style of" part.

**Comment by gucong3000** [comment]
First of all, @AI passed [this slides](http://slides.com/ai/stylelint#/) to clarify why it is necessary to use `stylelint` in project.
However, in our company, many projects use Vue components. `stylelint` cannot check the style sheet in `*. Vue` file.
So I created this tool so that `stylelint` can check the style sheet in `*. Vue` file.

**Comment by stevenvachon** [comment]
Ohh okay. Thank you. Perhaps put this in the readme to prevent confusion for others.
